server:
  port: 8080
  host: "0.0.0.0"

database:
  host: "localhost"
  port: 5432
  user: "postgres"
  password: "123456"
  dbname: "audit_system"
  sslmode: "disable"

jwt:
  secret: "your-secret-key"
  expire: 24

log:
  level: "debug"
  file: "logs/audit-system.log"
